### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by acatoire** [bash0/cewe2pdf#1]
Hi,
I am very interested in your script, did you try it with the last version of CEWE?

Because when I run it I Have this error
File "/cewe2pdf.py", line 128, in <module>
    fotobook.findall("./page[@pagenr='0'][@type='FULLCOVER']")
IndexError: list index out of range

**Comment by AnEnglishmanInNorway** [comment]
@acatoire 
Could we close this issue now, to keep the open issue list down to issues that are still relevant?
