### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by szkottipipen** [bash0/cewe2pdf#12]
I made the cewe_folder.txt and i filled it. Then i run the tool in the same folder with .mcf file, i get:

 ```
File "C:\cewe2\cewe2pdf.py", line 102
    print 'Could not find %s in %s paths' % (filename, ', '.join(paths))
                                        ^
SyntaxError: invalid syntax
```
What do I do wrong? Thanks!

**Comment by AnEnglishmanInNorway** [comment]
@szkottipipen: I think the current version is so far past the reporting of this issue that we should close it.

**Comment by AnEnglishmanInNorway** [comment]
Closed as part of a small administrative cleanup
