### ISSUE TITLE
No module named 'pkg_resources'

### ISSUE THREAD

**Issue by TheGoldenMan99** [bash0/cewe2pdf#127]
It doesn't work. What should I do?

Traceback (most recent call last):
  File "C:\Users\Luis\AppData\Local\cewe2pdf-master\cewe2pdf.py", line 90, in <module>
    from pkg_resources import parse_version
ModuleNotFoundError: No module named 'pkg_resources'

**Comment by AnEnglishmanInNorway** [comment]
I'm not at home right now to check further, but a quick search reveals that
this is not an uncommon error for other projects as well. Two suggestions I
found are...
    "pip install --upgrade setuptools"
or
    "pip install --force-reinstall -U setuptools"
Maybe you could try these and let us know if the problem goes away?

**Comment by TheGoldenMan99** [comment]
Thank you :) That seems to fix that error, but now I got a new one:


C:\Users\Luis\AppData\Local\cewe2pdf-master\cewe2pdf.py:90: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import parse_version
Traceback (most recent call last):
  File "C:\Users\Luis\AppData\Local\cewe2pdf-master\cewe2pdf.py", line 96, in <module>
    from clpFile import ClpFile  # for clipart .CLP and .SVG files
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Luis\AppData\Local\cewe2pdf-master\clpFile.py", line 7, in <module>
    import cairosvg
  File "C:\Users\Luis\AppData\Local\Programs\Python\Python312\Lib\site-packages\cairosvg\__init__.py", line 26, in <module>
    from . import surface  # noqa isort:skip
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Luis\AppData\Local\Programs\Python\Python312\Lib\site-packages\cairosvg\surface.py", line 9, in <module>
    import cairocffi as cairo
  File "C:\Users\Luis\AppData\Local\Programs\Python\Python312\Lib\site-packages\cairocffi\__init__.py", line 47, in <module>
    cairo = dlopen(
            ^^^^^^^
  File "C:\Users\Luis\AppData\Local\Programs\Python\Python312\Lib\site-packages\cairocffi\__init__.py", line 44, in dlopen
    raise OSError(error_message)  # pragma: no cover
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libcairo.so.2'
cannot load library 'libcairo.2.dylib': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libcairo.2.dylib'
cannot load library 'libcairo-2.dll': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libcairo-2.dll'

C:\Users\Luis\AppData\Local\cewe2pdf-master>



Do you know what to do? Maybe I did something wrong so that it doesn't work right away.

**Comment by AnEnglishmanInNorway** [comment]
Once again shooting from the hip since I'm not at home, but have you
installed cairo graphics? This is a package which is not python but must be
available on the machine. There are several ways to get it. Personally I
used Microsoft's vcpkg, https://vcpkg.io/en/.

**Comment by AnEnglishmanInNorway** [comment]
I think the simple fix for the deprecated pkg_resources issue is to replace
`from pkg_resources import parse_version`
with
`from packaging.version import parse as parse_version`
Thanks for that feedback, I've made that change in my fork. The change will surely percolate down to the bash0 version at some point
