### ISSUE TITLE
HEIC support

### ISSUE THREAD

**Issue by cbzittoun** [bash0/cewe2pdf#130]
I got an error as some of my pictures were .heic.
I managed to make it work by adding the following to `cewe2pdf.py`:

```
from pillow_heif import register_heif_opener
register_heif_opener()
```

Thanks for the lib, apart from that it delivered nicely.

**Comment by AnEnglishmanInNorway** [comment]
Hi! Nice to get an issue with a fix! I wonder how you managed to get the .heic picture into the album? When I add a .heic photo to the test album it seems to get automatically converted to a png. I'm running what claims to be version 7.3.4 of the program.

**Comment by cbzittoun** [comment]
I am on the same version.
Note I also had the mcfx issue (needed to extract files from the sqlite file as mentioned in the other issue https://github.com/bash0/cewe2pdf/issues/119).

**Comment by AnEnglishmanInNorway** [comment]
Aha. That could be the difference, perhaps they upgraded the photo import as well. I don't think anybody is enthusiastic about building in mcfx support right now, but I guess we'll have to do it one day. I just use "save as" mcf, but they'll probably remove that capability one day.

**Comment by cbzittoun** [comment]
I did not even know the "save as" even existed.
You should document it in your README, that would save lives.
Also for the mcfx support, you could just wrap the snippet people gave as a temp solution in the issue.

**Comment by AnEnglishmanInNorway** [comment]
Just added a note to the README about using Save as to .mcf format in the
album editor. But issue https://github.com/bash0/cewe2pdf/issues/119
remains open until somebody feels enthusiastic about unpacking the .mcfx in
our code.

**Comment by AnEnglishmanInNorway** [comment]
Just implemented handling of the .mfcx format, pull request #131
Once that was in place I thought I'd try a .heic file in the unittest album. However ... the entry in the data.mcf file inside the .mcfx file looks like this
```
        <foto id="file:///D:/temp/20210907_114921.heic">
            <foto id="safecontainer:/20210907_1_114921.png" nature="RELATIONSHIP_ONE_TO_ONE_COPY"/>
        </foto>
```
and the unpacked directory contains the .png version of the file, not the .heic.
In addition, the pdf comes out correctly _without the heif_opener_ as suggested by @cbzittoun. Perhaps the Linux version of the album editor behaves differently and doesn't do the automatic conversion to png. I guess adding the heif opener won't make any difference to a Windows run, so we could just include it anyway.
