### ISSUE TITLE
OpenType font `.otf` file support

### ISSUE THREAD

**Issue by cweiske** [bash0/cewe2pdf#133]
CEWE Fotowelt 7.4.3 ships `.otf` ([OpenType](https://en.wikipedia.org/wiki/OpenType)) fonts:
```
dm-fotowelt/Resources/photofun/fonts/CEWEHead-BoldItalic.otf
dm-fotowelt/Resources/photofun/fonts/CEWEHead-Bold.otf
dm-fotowelt/Resources/photofun/fonts/CEWEHead-Italic.otf
dm-fotowelt/Resources/photofun/fonts/CEWEHead-Regular.otf
dm-fotowelt/Resources/photofun/fonts/LiebeDoris-Bold.otf
dm-fotowelt/Resources/photofun/fonts/LiebeErika-Medium.otf
dm-fotowelt/Resources/photofun/fonts/LiebeGerda-BoldItalic.otf
```

Those fonts do not get loaded by cewe2pdf, leading to warnings like
> WARNING:root:Using font family = 'Helvetica' (wanted CEWE Head)

Simply loading them will also fail with
> ERROR:cewe2pdf.config:Failed to register font 'CEWE Head Bold' (from [...]/Resources/photofun/fonts/CEWEHead-Bold.otf)
because:
> TTF file "[...]/Resources/photofun/fonts/CEWEHead-Bold.otf": postscript outlines are not supported

OpenType fonts may contain the glyph (letter) outlines in two formats: "TrueType outlines" and "CFF outlines" (PostScript).
Reportlab's PDF library `python3-reportlab` only supports TrueType outlines but not PostScript outlines, [since 2013](https://reportlab-users.reportlab.narkive.com/dnc3Oxy4/otf-fonts-supported-by-reportlab).

It seems all `.otf` files shipped with Fotowelt are using PostScript/CFF outlines - you can check that with the "[otfinfo](http://www.lcdf.org/type/otfinfo.1.html)" from `lcdf-typetools`:
```
for i in Resources/photofun/fonts/*.otf; do echo "$i"; otfinfo -t "$i" | grep CFF; done
Resources/photofun/fonts/CEWEHead-BoldItalic.otf
  32158 CFF
Resources/photofun/fonts/CEWEHead-Bold.otf
  33827 CFF
Resources/photofun/fonts/CEWEHead-Italic.otf
  31675 CFF
Resources/photofun/fonts/CEWEHead-Regular.otf
  33126 CFF
Resources/photofun/fonts/LiebeDoris-Bold.otf
  99823 CFF
Resources/photofun/fonts/LiebeErika-Medium.otf
  53244 CFF
Resources/photofun/fonts/LiebeGerda-BoldItalic.otf
2522236 CFF
```

(Why they ship multiple files for "CEWE Head" is a mystery; `.otf` allows multiple variants to be combined into a single file.)

Since cewe2pdf deeply integrates with reportlab's pdf generator, there is no support for PostScript `.otf` fonts in sight.

----

`.otf` font files can be converted to `.ttf` with fontforge:
```
for i in /path/to/cewe/Resources/photofun/fonts/*.otf; do\
    echo $i;\
    filename=$(basename "$i");\
    fontforge -lang=ff -c 'Open($1); Generate($2); Close();' "$i" "$filename.ttf";\
done
```

----

How can we help normal users solving the `.otf` problem?

I see two options:
- Warn them when the cewe folder contains `.otf` files (easy, but leads to false warnings when no `.otf` files are used in the book)
- Warn them when an font cannot be found but an `.otf` file for it is available (harder to implement but gives better results)
- Transparently convert `.otf` to `.ttf`, e.g. via https://github.com/awesometoolbox/otf2ttf

**Comment by AnEnglishmanInNorway** [comment]
Nice investigation. I don't use CEWE Head or the others so I have never noticed this. I prefer your solutions in reverse order! The otf2tff code didn't look as though it should be too tricky to integrate. We should find a good common place to the put the resulting tff files (so we don't need special permissions to write to the system font directories) and the conversion would then be a one-off, the first time an otf font was used.
An interesting secondary point is what we regard as a "normal" user of cewe2pdf. It does require a certain level of programming skills to get the environment set up (unless we let it loose in a freestanding pyinstall/pysetup version, something that I am not sure we want to do outside of family and friends, who of course have access to our own skills)
