### ISSUE TITLE
Error/warning summary at the end of pdf generation

### ISSUE THREAD

**Issue by cweiske** [bash0/cewe2pdf#147]
I'm converting a 54 page book into PDF and get lots of output. Many of it is debug output, but here and there are warnings between the hundreds of output lines.

It would be nice if there was a summary line that told how many errors and warnings there were, and in which categories the warnings fell.

Example:
```
Summary: 4 errors, 23 warnings
- 4x font error
- 12x font warning
- 68x passepartout
- 2x clipart
- 1x clipart color substitution 
```

**Comment by AnEnglishmanInNorway** [comment]
Nice idea. Getting the logging level right is tricky in any project.
Another related thought might be a finer granularity in the logging.
Clipart is a topic we could introduce. Then when the number of clipart
related messages in the summary was high that would suggest that the
clipart logging level could be increased.
I didn't realise that passepartout was used much. Useful to know.

**Comment by AnEnglishmanInNorway** [comment]
I wonder if the best strategy here might be to build a "counting" wrapper around logging and use that everywhere we use logging.whatever
