### ISSUE TITLE
More specific "WARNING:root:Frames (passepartout) are not fully implemented"

### ISSUE THREAD

**Issue by cweiske** [bash0/cewe2pdf#148]
Whenever a passepartout is used, a warning message is shown:
> WARNING:root:Frames (passepartout) are not fully implemented 112021

When photo books have hundreds of them, they swamp the output.

I have not yet seen a passepartout frame that had problems, so we should not log this warning anymore unless we see a property that cewe2pdf does not support yet.

**Comment by AnEnglishmanInNorway** [comment]
Fair enough. I don't use passepartout, so your positive experience with their use is good enough for me! Dump the warning next time you're in the code.
