### ISSUE TITLE
Line height wrong (line_scale): Need 1.43 instead of 1.1

### ISSUE THREAD

**Issue by cweiske** [bash0/cewe2pdf#153]
In my current photo book, I head to increase the line_scale from 1.1 to 1.43 to get the same output as the cewe software. (Font: Crafty Girls)

I'll provide a demo mcfx file.

**Comment by AnEnglishmanInNorway** [comment]
The whole book? Or just some texts? All fonts or just specific fonts?
I'm not sure we've ever taken account of variation in the vertical spacing
(or even tried to discover how it is controlled by cewe)

**Comment by AnEnglishmanInNorway** [comment]
I was curious about this! There are several sources for the Crafty Girls Regular font (nice handwriting font, by the way!)
I downloaded from [Google](https://fonts.google.com/specimen/Crafty+Girls). The first problem is that our code doesn't look in the "personally installed fonts" location on Windows, I'll be adding a fix for that. Once that's in place, I agree, the spacing needs to be increased. What I can't find out is how Cewe knows that! A couple of useful links
- https://www.myfonts.com/pages/fontscom-learning-fontology-level-2-text-typography-line-spacing-for-text
- https://practicaltypography.com/line-spacing.html
- https://eng.fontke.com/font/15620749/detail/

The last one contains some "Measurement details" for the font, which might help us if we can (a) understand what they are and (b) find them programmatically for all fonts

**Comment by cweiske** [comment]
When you're at it, add `~/.local/share/fonts/` as possible font location

It's `$XDG_DATA_HOME` + `/fonts/`, but when XDG_DATA_HOME is not defined its default is `~/.local/share`. We already use this in `pathutils.py`.

- https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
- (german) https://blog.thul.org/technik/betriebssysteme/verzeichnis-fuer-benutzerschriftarten/

**Comment by AnEnglishmanInNorway** [comment]
My research leads me to believe that there is no real way to find "the best" line spacing for a font. The choice depends on many factors, and is determined largely by the visual effect that the graphic designer wants to achieve in the particular text layout. There could be some way to guess based on the "x-height" of the font combined with the height of the ascenders and descenders, but I don't think that's within reach for us. Our current default line_scale (1.1) is probably formally a bit tight (1.2 to 1.6 seems to be a normal range) but it is clearly giving us all something good enough for our purposes. I wonder if the best solution for Crafty Girls and other similar cases would be to add a table to the _cewe2pdf.ini_ file in which we could set the line_scale for particular fonts. Something along the lines of
```
lineScales =
	Crafty Girls Regular, 1.43
	Arial Rounded Bold MT, 1.2
```

This would change the line_scale for **all** uses of the font, and would be applied before any line spacing set for an individual text box (without having checked, I'm not at all sure that we handle such an individual setting anyway!)

Any better ideas?

**Comment by cweiske** [comment]
This sounds like a good idea, since nobody knows how to automatically determine the line heights that the cewe software uses.
