### ISSUE TITLE
RFE: information for *.webp backgrounds and sample font file

### ISSUE THREAD

**Issue by truatpasteurdotfr** [bash0/cewe2pdf#17]
thanks for this great tool!

I had a 6363.webp backgroung which was expected to be a 6363.bmp format. 

```
Could not find 6363.bmp in /c7/shared/cewe/6.4.7/Resources/photofun/backgrounds, /c7/shared/cewe/6.4.7/Resources/photofun/backgrounds/einfarbige, /c7/shared/cewe/6.4.7/Resources/photofun/backgrounds/multicolor paths
...
```
Solution: use dwep from libwebp-tools (epel on centos7) or https://developers.google.com/speed/webp/docs/precompiled to convert the webp to bmp.

```
dwebp ./Resources/photofun/backgrounds/6363.webp -o./Resources/photofun/backgrounds/6363.bmp
```
additional_fonts.txt sample:
```
Elegant Script = /c7/shared/cewe/6.4.7/Resources/photofun/fonts/Elegant-Script.ttf
```

**Comment by BarchSteel** [comment]
The current versions can use .webp directly.

**Comment by AnEnglishmanInNorway** [comment]
Nice. Maybe this item could be closed now?
