### ISSUE TITLE
passepartout.py", line 99, in Passepartout def buildElementIdIndex(directoryList: list[str]) -> dict: TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by monoeagle** [bash0/cewe2pdf#180]
Hi,

System: Linux

- Installed Cairographics Support and used the commandline to install the python dependencies.
-> Python 3.8.10 installed
- Added the Photobook DIR in the ini file.
 
If I try to use cewe2pdf.py I get the following error message:

`
python3 cewe2pdf.py /home/user/desktop/photobooks/2021.mcf 
Traceback (most recent call last):
  File "cewe2pdf.py", line 103, in <module>
    from passepartout import Passepartout
  File "/home/user/apps/cewe2pdf/passepartout.py", line 20, in <module>
    class Passepartout():
  File "/home/user/apps/cewe2pdf/passepartout.py", line 99, in Passepartout
    def buildElementIdIndex(directoryList: list[str]) -> dict:
TypeError: 'type' object is not subscriptable

`

What is the problem? Missed some other prereqs?

greetz

**Comment by AnEnglishmanInNorway** [comment]
A quick search on the net suggests that your Python is too old for the syntax used in passepartout.py (and more than likely in other places in the code). You'll need 3.9 or higher. The cewe2pdf project uses 3.10.4 for the checkin builds, so that's a good bet.

**Comment by monoeagle** [comment]
After 7h of migration from v18 to the latest linux mint v22 now we have the python version: 3.12.3  :)

First of all the first pdf is created.
But with Errors.

`
>>> Using additional font definitions from: ./additional_fonts.txt
22:55:56 - cewe2pdf.config - ERROR - Custom additional font file does not exist: C:\Windows\Fonts\BOD_R.TTF
22:55:56 - cewe2pdf.config - ERROR - Custom additional font file does not exist: /home/user/CEWE/CEWE Fotowelt\Resources\photofun\fonts\Function-Light.ttf
22:55:56 - cewe2pdf.config - ERROR - Custom additional font file does not exist: /home/cweiske/.local/share/fonts/
22:55:56 - cewe2pdf.config - ERROR - Custom additional font file does not exist: C:\Windows\Fonts\
>>> Scanning for ttf/otf files in ['/home/user/CEWE/CEWE Fotowelt/Resources/photofun/fonts']
22:55:56 - cewe2pdf.config - WARNING - One-time font conversion otf->ttf: /home/user/.local/share/cewe2pdf/LiebeDoris-Bold.ttf
22:55:57 - cewe2pdf.config - WARNING - One-time font conversion otf->ttf: /home/user/.local/share/cewe2pdf/LiebeErika-Medium.ttf
22:55:57 - cewe2pdf.config - WARNING - One-time font conversion otf->ttf: /home/user/.local/share/cewe2pdf/CEWEHead-Regular.ttf
22:55:57 - cewe2pdf.config - WARNING - One-time font conversion otf->ttf: /home/user/.local/share/cewe2pdf/CEWEHead-Bold.ttf
22:55:58 - cewe2pdf.config - WARNING - One-time font conversion otf->ttf: /home/user/.local/share/cewe2pdf/CEWEHead-Italic.ttf
22:55:58 - cewe2pdf.config - WARNING - One-time font conversion otf->ttf: /home/user/.local/share/cewe2pdf/CEWEHead-BoldItalic.ttf
22:55:58 - cewe2pdf.config - WARNING - Revised regular fontFullName 'Alegreya Sans Regular' to 'Alegreya Sans'
22:55:58 - cewe2pdf.config - WARNING - Revised regular fontFullName 'Amatic SC Regular' to 'Amatic SC'
22:55:58 - cewe2pdf.config - WARNING - fontFullName == fontFamily 'Balloon Caps' for a non-regular subfamily 'Xbold'. A bit strange!
22:55:58 - cewe2pdf.config - WARNING - fontFullName == fontFamily 'FranklinGothic' for a non-regular subfamily 'Medium'. A bit strange!
22:55:58 - cewe2pdf.config - WARNING -   constructed fontFullName 'FranklinGothic Medium' for 'FranklinGothic' 'Medium'
22:55:58 - cewe2pdf.config - WARNING - fontFullName == fontFamily 'FranklinGothic' for a non-regular subfamily 'Medium Italic'. A bit strange!
22:55:58 - cewe2pdf.config - WARNING -   constructed fontFullName 'FranklinGothic Medium Italic' for 'FranklinGothic' 'Medium Italic'
22:55:58 - cewe2pdf.config - WARNING - Revised regular fontFullName 'Istok Web Regular' to 'Istok Web'
22:55:58 - cewe2pdf.config - WARNING - fontFullName == fontFamily 'Pecita' for a non-regular subfamily 'Book'. A bit strange!
22:55:58 - cewe2pdf.config - WARNING - Unhandled fontSubFamily 'Book', using fontFamily 'Pecita' as the regular font name
22:55:58 - cewe2pdf.config - WARNING - Revised regular fontFullName 'CEWE Head Regular' to 'CEWE Head'
22:55:58 - root - INFO - Registering 83 fonts
22:55:58 - cewe2pdf.config - WARNING - Font family 'Balloon Caps' has no normal font, chosen Balloon Caps from bold
22:55:58 - cewe2pdf.config - WARNING - Font family 'Micro' has no normal font, chosen Micro Medium from bold
22:55:58 - cewe2pdf.config - WARNING - Font family 'Typewriter' has no normal font, chosen Typewriter Medium from bold
22:55:58 - cewe2pdf.config - WARNING - Font family 'LiebeDoris' has no normal font, chosen LiebeDoris Bold from bold
22:55:58 - root - INFO - Ended font registration
22:55:59 - root - INFO - parsing page 0  of 48
22:56:00 - root - WARNING - A set of paragraphs would not fit inside its frame. Frame height is increased to prevent loss of text.
22:56:00 - root - WARNING -  Try widening the text box just slightly to avoid an unexpected word wrap, or increasing the height yourself
22:56:00 - root - WARNING -  Most recent paragraph text: <para autoLeading="max"><font name="CEWE Head" size=48 color=#ffffff>Tour 2021</font></para>
22:56:00 - root - INFO - parsing page 1  of 48
22:56:00 - root - INFO - parsing page 0  of 48
22:56:00 - root - INFO - parsing page 2  of 48
22:56:03 - root - ERROR - Error: Opening and ending tag mismatch: icon line 248 and icons, line 987, column 9 (icons-liste.xml, line 987)
22:56:03 - root - ERROR - Error: Start tag expected, '<' not found, line 1, column 1 (smile_model.xml, line 1)
22:56:03 - root - ERROR - Can't find passepartout for 126822
22:56:04 - root - ERROR - Can't find passepartout for 126822
22:56:04 - root - INFO - parsing page 3  of 48
22:56:04 - root - ERROR - Can't find passepartout for 74127
22:56:04 - root - ERROR - Problem getting file name for clipart ID: 46117
22:56:04 - root - ERROR - Problem getting file name for clipart ID: 45733
22:56:04 - root - INFO - parsing page 4  of 48
22:56:04 - root - ERROR - Problem getting file name for clipart ID: 432103
22:56:05 - root - ERROR - Problem getting file name for clipart ID: 46118
22:56:05 - root - ERROR - Problem getting file name for clipart ID: 45733
22:56:05 - root - INFO - parsing page 5  of 48
22:56:05 - root - ERROR - Can't find passepartout for 128251
22:56:05 - root - INFO - parsing page 6  of 48
22:56:06 - root - ERROR - Can't find passepartout for 128090
22:56:06 - root - INFO - parsing page 7  of 48
22:56:08 - root - INFO - parsing page 8  of 48
22:56:08 - root - INFO - parsing page 9  of 48
22:56:09 - root - INFO - parsing page 10  of 48
22:56:09 - root - ERROR - Can't find passepartout for 126818
22:56:10 - root - ERROR - Problem getting file name for clipart ID: 458100
22:56:10 - root - WARNING - Using font family = 'CEWE Head' (wanted Sans Serif)
22:56:10 - root - INFO - parsing page 11  of 48
22:56:10 - root - ERROR - Can't find passepartout for 128246
22:56:10 - root - INFO - parsing page 12  of 48
22:56:11 - root - ERROR - Can't find passepartout for 74127
22:56:11 - root - ERROR - Can't find passepartout for 74127
22:56:12 - root - ERROR - Can't find passepartout for 74127
22:56:12 - root - INFO - parsing page 13  of 48
22:56:13 - root - INFO - parsing page 14  of 48
22:56:13 - root - INFO - parsing page 15  of 48
22:56:14 - root - ERROR - Can't find passepartout for 74127
22:56:15 - root - ERROR - Can't find passepartout for 109959
22:56:15 - root - INFO - parsing page 16  of 48
22:56:16 - root - INFO - parsing page 17  of 48
22:56:16 - root - ERROR - Can't find passepartout for 74127
22:56:17 - root - ERROR - Can't find passepartout for 74127
22:56:17 - root - INFO - parsing page 18  of 48
22:56:18 - root - ERROR - Can't find passepartout for 128250
22:56:20 - root - INFO - parsing page 19  of 48
22:56:20 - root - INFO - parsing page 20  of 48
22:56:22 - root - INFO - parsing page 21  of 48
22:56:22 - root - INFO - parsing page 22  of 48
22:56:22 - root - INFO - parsing page 23  of 48
22:56:23 - root - INFO - parsing page 24  of 48
22:56:24 - root - INFO - parsing page 25  of 48
22:56:25 - root - INFO - parsing page 26  of 48
22:56:25 - root - INFO - parsing page 27  of 48
22:56:26 - root - INFO - parsing page 28  of 48
22:56:26 - root - INFO - parsing page 29  of 48
22:56:29 - root - INFO - parsing page 30  of 48
22:56:32 - root - ERROR - Can't find passepartout for 128091
22:56:32 - root - INFO - parsing page 31  of 48
22:56:33 - root - INFO - parsing page 32  of 48
22:56:34 - root - INFO - parsing page 33  of 48
22:56:35 - root - INFO - parsing page 34  of 48
22:56:37 - root - INFO - parsing page 35  of 48
22:56:38 - root - INFO - parsing page 36  of 48
22:56:38 - root - INFO - parsing page 37  of 48
22:56:40 - root - INFO - parsing page 38  of 48
22:56:41 - root - INFO - parsing page 39  of 48
22:56:42 - root - INFO - parsing page 40  of 48
22:56:42 - root - ERROR - Problem getting file name for clipart ID: 46098
22:56:42 - root - INFO - parsing page 41  of 48
22:56:43 - root - ERROR - Problem getting file name for clipart ID: 46098
22:56:43 - root - ERROR - Problem getting file name for clipart ID: 46097
22:56:43 - root - ERROR - Problem getting file name for clipart ID: 46113
22:56:43 - root - ERROR - Problem getting file name for clipart ID: 46095
22:56:43 - root - ERROR - Problem getting file name for clipart ID: 46115
22:56:43 - root - INFO - parsing page 42  of 48
22:56:43 - root - INFO - parsing page 43  of 48
22:56:44 - root - ERROR - Problem getting file name for clipart ID: 46097
22:56:44 - root - INFO - parsing page 44  of 48
22:56:46 - root - ERROR - Problem getting file name for clipart ID: 46111
22:56:46 - root - INFO - parsing page 45  of 48
22:56:47 - root - ERROR - Problem getting file name for clipart ID: 46111
22:56:47 - root - INFO - parsing page 46  of 48
22:56:47 - root - ERROR - Problem getting file name for clipart ID: 46099
22:56:47 - root - ERROR - Can't find passepartout for 127229
22:56:48 - root - INFO - parsing page 0  of 48
22:56:48 - root - WARNING - A set of paragraphs would not fit inside its frame. Frame height is increased to prevent loss of text.
22:56:48 - root - WARNING -  Try widening the text box just slightly to avoid an unexpected word wrap, or increasing the height yourself
22:56:48 - root - WARNING -  Most recent paragraph text: <para autoLeading="max"><font name="CEWE Head" size=48 color=#ffffff>Tour 2021</font></para>
22:56:49 - root - INFO - GC collected objects : 81
Total message counts, including messages suppressed by logger configuration
cewe2pdf.config: ERROR[4], WARNING[21], INFO[151]
root:            ERROR[35], WARNING[8], INFO[53]
`

The positions of some Elements are not corrent. Also the scaling of pictures.

What can I do?

**Comment by AnEnglishmanInNorway** [comment]
Wow. That was a mammoth upgrade. Looking at the messages I wonder if you have forgotten to configure `cewe2pdf `for your local system and installation, in particular because you are clearly using the "additional_fonts.txt" file from the program directory. 

Take a look at the section on configuration files in the [README](https://github.com/bash0/cewe2pdf/blob/master/README.md). The best thing to do is to create a local copy of `cewe2pdf.ini` and `additional_fonts.txt` next to your album file, and make those reflect your installation. The absolutely most important entry is `cewe_folder` in the .ini file, which should allow the code to locate the Cewe data - things like the Cewe fonts, clip arts, passepartout frames, and so on.

**Comment by monoeagle** [comment]
thx for the fast response.

The path for cewe I wrote into the cewe2pdf.ini .
That was the only step I have done.

Now I removed all entries in the additional_fonts.txt.

The errors are still there.

In the following DIR are the cliparts (clp files): 
/home/user/CEWE/CEWE Fotowelt/Resources/photofun/decorations

But the error messages are OK, because in the DIR the called numbers are missing. *hmmm*
The crazy thing some picture frames in the PDF are correct, als the same picture frame on another site is missing.
The same type of picture frame. In Cewe I can klick to "find frame" and the picture frame is located in the library.

If I save the book in the never mcfx format, it's the same.

"22:56:11 - root - ERROR - Can't find passepartout for 74127"

At the moment I don't understand what a passpartout is, is that a clipart as well and have to be in the same decorations DIR? The 74127 also didn't exist there.

The Cewe software is the version 7.4.3 (x64) and normally it checks itself if there are any updates.

**Comment by monoeagle** [comment]
`
10:39:07 - root - INFO - Ended font registration
10:39:07 - root - INFO - parsing page 0  of 48
10:39:07 - root - WARNING - A set of paragraphs would not fit inside its frame. Frame height is increased to prevent loss of text.
10:39:07 - root - WARNING -  Try widening the text box just slightly to avoid an unexpected word wrap, or increasing the height yourself
10:39:07 - root - WARNING -  Most recent paragraph text: <para autoLeading="max"><font name="CEWE Head" size=48 color=#ffffff>Tour 2021</font></para>
10:39:07 - root - INFO - parsing page 1  of 48
10:39:07 - root - INFO - parsing page 0  of 48
10:39:07 - root - INFO - parsing page 2  of 48
10:39:08 - root - ERROR - Error: Opening and ending tag mismatch: icon line 248 and icons, line 987, column 9 (icons-liste.xml, line 987)
10:39:08 - root - ERROR - Error: Start tag expected, '<' not found, line 1, column 1 (smile_model.xml, line 1)
10:39:10 - root - INFO - parsing page 3  of 48
10:39:10 - root - INFO - parsing page 4  of 48
10:39:10 - root - INFO - parsing page 5  of 48
10:39:11 - root - INFO - parsing page 6  of 48
10:39:12 - root - INFO - parsing page 7  of 48
10:39:14 - root - INFO - parsing page 8  of 48
10:39:14 - root - INFO - parsing page 9  of 48
10:39:15 - root - INFO - parsing page 10  of 48
10:39:16 - root - WARNING - Using font family = 'CEWE Head' (wanted Sans Serif)
10:39:16 - root - INFO - parsing page 11  of 48
10:39:16 - root - INFO - parsing page 12  of 48
10:39:19 - root - INFO - parsing page 13  of 48
10:39:20 - root - INFO - parsing page 14  of 48
10:39:20 - root - INFO - parsing page 15  of 48
10:39:23 - root - INFO - parsing page 16  of 48
10:39:23 - root - INFO - parsing page 17  of 48
10:39:26 - root - INFO - parsing page 18  of 48
10:39:28 - root - INFO - parsing page 19  of 48
10:39:29 - root - INFO - parsing page 20  of 48
10:39:30 - root - INFO - parsing page 21  of 48
10:39:30 - root - INFO - parsing page 22  of 48
10:39:30 - root - INFO - parsing page 23  of 48
10:39:31 - root - INFO - parsing page 24  of 48
10:39:32 - root - INFO - parsing page 25  of 48
10:39:32 - root - INFO - parsing page 26  of 48
10:39:33 - root - INFO - parsing page 27  of 48
10:39:34 - root - INFO - parsing page 28  of 48
10:39:34 - root - INFO - parsing page 29  of 48
10:39:36 - root - INFO - parsing page 30  of 48
10:39:38 - root - INFO - parsing page 31  of 48
10:39:40 - root - INFO - parsing page 32  of 48
10:39:40 - root - INFO - parsing page 33  of 48
10:39:41 - root - INFO - parsing page 34  of 48
10:39:43 - root - INFO - parsing page 35  of 48
10:39:44 - root - INFO - parsing page 36  of 48
10:39:44 - root - INFO - parsing page 37  of 48
10:39:46 - root - INFO - parsing page 38  of 48
10:39:46 - root - INFO - parsing page 39  of 48
10:39:47 - root - INFO - parsing page 40  of 48
10:39:48 - root - INFO - parsing page 41  of 48
10:39:48 - root - INFO - parsing page 42  of 48
10:39:48 - root - INFO - parsing page 43  of 48
10:39:49 - root - INFO - parsing page 44  of 48
10:39:52 - root - INFO - parsing page 45  of 48
10:39:52 - root - INFO - parsing page 46  of 48
10:39:53 - root - INFO - parsing page 0  of 48
10:39:53 - root - WARNING - A set of paragraphs would not fit inside its frame. Frame height is increased to prevent loss of text.
10:39:53 - root - WARNING -  Try widening the text box just slightly to avoid an unexpected word wrap, or increasing the height yourself
10:39:53 - root - WARNING -  Most recent paragraph text: <para autoLeading="max"><font name="CEWE Head" size=48 color=#ffffff>Mutter + Sohn Tour 2021</font></para>
10:39:54 - root - INFO - GC collected objects : 498
Total message counts, including messages suppressed by logger configuration
cewe2pdf.config: WARNING[15], INFO[157]
root:            ERROR[2], WARNING[8], INFO[57]
`

I removed/replaced all missing picture frame and cliparts.
CEWE removed them! 

I'll backup the DIR and will compare after an update.

The last problem I have is that some text elements are not correct.
Sometime the "tabulator" and a empty Line is ignored that's why some exported text elements are crappy.

Any hint?

**Comment by monoeagle** [comment]
I tried the following:

1. Edit the old project which is new saved as mcfx.
2. remove text element -> add new text element
3. used tabs and used whitespace or newlines
4. tried new fresh project add text element tried the same as in 3.

same crappy output

![result in PDF](https://github.com/user-attachments/assets/eeef7955-b0fa-4a0e-8ef1-9a08a9729cc8)
![cewe editor](https://github.com/user-attachments/assets/ff30a534-808a-4358-89cf-d2a1d661cff8)
 
(names removed)

Is it a config error on my side or a bug?

**Comment by AnEnglishmanInNorway** [comment]
OK. Lots of stuff to look at here. 

First off, I'm pretty sure you are right - line spacing (as set by the user in the Cewe editor in the text editing tab) is not implemented, I guess because none of the contributors to the program as it stands today have ever used/needed  it. You could make a separate issue out of that one thing, so it is noted. Perhaps you could implement it yourself if it is very important to your work. BTW, it is important to distinguish between the "line spacing" set in the editor (which results in a lineHeight attribute which appears to specify a percentage - i.e. setting 1.7 in the editor gives lineHeight="170") and what we have termed the font lineScale, which is a characteristic of a font and says how much space should be used between lines by default (this is called the leading in the printing industry, because in real old-fashioned typesetting they actually put lead bars between the lines of lead type)

Tabs and white space. Yes. Mmm. My advice would be to find an alternative way of formatting your text. I personally looked at this some years back, and I never found what I thought was a clear and unambiguous way of interpreting what was in the xml. It could also be that the reportlabs package doesn't support tabbing very well, I guess. Once again, you're welcome to have a go at a better implementation if it's very important to you.

These error messages are really worth looking at. 
```
10:39:53 - root - WARNING - A set of paragraphs would not fit inside its frame. Frame height is increased to prevent loss of text.
10:39:53 - root - WARNING - Try widening the text box just slightly to avoid an unexpected word wrap, or increasing the height yourself
10:39:53 - root - WARNING - Most recent paragraph text: Tour 2021
```
The messages are telling you that the pdf which has been created by the reportlabs package for a piece of text does not fit into the space available. I can only imagine that reportlabs and Cewe do not quite agree on how the widths of the letters and spacing in a font go together. It doesn't seem to be something we can do much about, so our message is giving you a serious hint that you should widen your text box slightly. Ignore that message and you will probably get a line break that you didn't expect, as your pictures appear to demonstrate. (And , BTW, if I may be so bold, "crappy" is not a word I'd use in this context. It has very negative connotations and might not encourage helpful answers! "Unexpected" is a good neutral description :-) )

One good way of getting "wrong width" text is not to have all the correct fonts available. I see that you have a message about "Sans Serif" being missing. I have a Windows box, so I don't know what the font setup on Ubuntu looks like, but perhaps you have used a system font rather than a Cewe font, and not told cewe2pdf where that font file is? On that subject, I see that your picture from the Cewe editor is using a serif-ed font, while the pdf has substituted a sans-serif font, so there is definitely some kind of mismatch in your font definitions.

Then there are these:
```
10:39:08 - root - ERROR - Error: Opening and ending tag mismatch: icon line 248 and icons, line 987, column 9 (icons-liste.xml, line 987)
10:39:08 - root - ERROR - Error: Start tag expected, '<' not found, line 1, column 1 (smile_model.xml, line 1)
```
I imagine we all get these. They are genuine errors in the supplied Cewe configuration files, but I've never noticed any effect.

Hope these hints get you a bit closer to a pdf which you can use.

**Comment by monoeagle** [comment]
Thx for your answer. I'll use more unexpected than "crappy". ;) 
As a non-native speaker it was first in my mind. :) brain -> reorg ;)

The Feature I tried was LineSpacing in the font properties of a textelement.

Tabs and white Space:
I was happy to find cewe2pdf. My python programming skills are very bad so I have to learn 
a lot more. But everyone starts with low skills. ;)

The first warning block can be ignored.

The sans serif message I can't understand because as Default "CEWE Head" is selected and on that page 
isn't a textbox with sans serif. As I remember that book is build on a windows machine in 2021.

Thanks I'll close that issue.
