### ISSUE TITLE
File "cewe2pdf.py" line 1679 match productstyle

### ISSUE THREAD

**Issue by d7071** [bash0/cewe2pdf#190]
Hi there,

I get a >File "cewe2pdf.py" line 1679 match productstyle< message.

I have double checked all paths. I am not aware what else I should do.
I am using WLS on a windows 10 machine. Everything runs under windows only python is installed on WSL.

I also checked that windows paths are provided by proper UNIX paht (/mnt/c/Windows.....). 

Can anyone give a hint hot to proceed

Thanks in advance.

**Comment by AnEnglishmanInNorway** [comment]
Ouch. That's likely to be my fault. The match statement was introduced in Python 3.10, while our description says you need 3.9, which I _guess_ you are using. It'll be a while before I get to my coding environment so your immediate choices are to upgrade your Python version or to recode that one match statement into a set of if statements in your fork.

BTW, I wonder why you are using WSL on your Windows PC? I run cewe2pdf natively on a Windows 10 PC, in an Anaconda environment. I have WSL as well so I can test there once in a while, but don't really see any advantage.

**Comment by d7071** [comment]
I have updated to python 3.12 now. The error message is like:

Traceback (most recent call last):
  File "/home/maik/cewe2pdf/cewe2pdf.py", line 83, in <module>
    from reportlab.pdfgen import canvas
  File "/usr/lib/python3/dist-packages/reportlab/pdfgen/canvas.py", line 19, in <module>
    from reportlab import rl_config, ascii, xrange
  File "/usr/lib/python3/dist-packages/reportlab/rl_config.py", line 45, in <module>
    _DEFAULTS=_defaults_init()
              ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/reportlab/rl_config.py", line 13, in _defaults_init
    from reportlab.lib.utils import rl_exec
  File "/usr/lib/python3/dist-packages/reportlab/lib/utils.py", line 10, in <module>
    from base64 import decodestring as base64_decodestring, encodestring as base64_encodestring
ImportError: cannot import name 'decodestring' from 'base64' (/usr/lib/python3.12/base64.py)


The reason I'd like to use WSL is because I like to keep my Windows machine clean. However, I am not very into that python stuff and I did not get it running on windows neither.

Thanks

________________________________

**Comment by AnEnglishmanInNorway** [comment]
That looks worse. It appears that the underlying reportlabs package isn't
initialising properly, and I have really no idea why. It's not impossible
that there's a compatibility issue between the various packages when you
move all the way to 3.12, or perhaps between the versions of the other
packages in requirements.txt. I think there's a warning in the description
about moving farther than Python 3.10 which is what is used by the checkin
builds on Github. Not much help, I fear, but that's the best i can offer

**Comment by Dobatymo** [comment]
`base64.encodestring()` was removed in Python 3.9. It looks your `reportlab` dependency is out of date...

**Comment by d7071** [comment]
Ok, sounds like going back to python 3.9? Sorry haven't spent much time in debugging.

Cheers
Maik

________________________________

**Comment by AnEnglishmanInNorway** [comment]
Back at my PC again so I've checked my own environment. I do my coding on Windows 10, using Visual Studio 2022 Community Edition as my interactive development environment and Anaconda as my Python command line environment. Hopefully this information will help you to find a consistent setup. I do have a vague memory of trying to update to a later reportlab version and hitting problems with that.

I'm using Python 3.12 (even though cewe2pdf recommends no further than 3.10):
```
(base) D:\Users\...\cewe2pdf>python --version
Python 3.12.4
```
I've installed pip-tools so that I can get a decent listing of the packages which I have installed:
```
python -m pip install pip-tools
pip-compile requirements.txt --output-file requirements-all.txt
```
which gives me this package listing, including notes as to why a package was required:
```
#
# This file is autogenerated by pip-compile with Python 3.12
# by the following command:
#
#    pip-compile --output-file=requirements-all.txt requirements.txt
#
astroid==3.3.6
    # via pylint
cairocffi==1.7.1
    # via cairosvg
cairosvg==2.7.1
    # via -r requirements.txt
cffi==1.17.1
    # via cairocffi
chardet==5.2.0
    # via reportlab
colorama==0.4.6
    # via
    #   pylint
    #   pytest
cssselect2==0.7.0
    # via cairosvg
defusedxml==0.7.1
    # via cairosvg
deprecated==1.2.15
    # via pikepdf
dill==0.3.9
    # via pylint
flake8==7.1.1
    # via -r requirements.txt
fonttools==4.55.3
    # via -r requirements.txt
iniconfig==2.0.0
    # via pytest
isort==5.13.2
    # via pylint
lxml==5.3.0
    # via
    #   -r requirements.txt
    #   pikepdf
mccabe==0.7.0
    # via
    #   flake8
    #   pylint
packaging==23.2
    # via
    #   -r requirements.txt
    #   pikepdf
    #   pytest
pikepdf==9.4.2
    # via -r requirements.txt
pillow==11.0.0
    # via
    #   -r requirements.txt
    #   cairosvg
    #   pikepdf
    #   reportlab
platformdirs==4.3.6
    # via pylint
pluggy==1.5.0
    # via pytest
pycodestyle==2.12.1
    # via flake8
pycparser==2.22
    # via cffi
pyflakes==3.2.0
    # via flake8
pylint==3.3.2
    # via -r requirements.txt
pytest==8.3.4
    # via -r requirements.txt
pyyaml==6.0.2
    # via -r requirements.txt
reportlab==4.2.5
    # via -r requirements.txt
tinycss2==1.4.0
    # via
    #   cairosvg
    #   cssselect2
tomlkit==0.13.2
    # via pylint
webencodings==0.5.1
    # via
    #   cssselect2
    #   tinycss2
wrapt==1.17.0
    # via deprecated
```

**Comment by AnEnglishmanInNorway** [comment]
Fixed the original title for this issue, but the problem diverged a bit from that. If that is still unresolved, @d7071, you'll perhaps want to open a new issue to chase down your python and package installation issue?
