### ISSUE TITLE
Background to the right

### ISSUE THREAD

**Issue by shutterbug79** [bash0/cewe2pdf#2]
Thanks for an awesome script, much appreciated. 

I found one issue. Images set as ‘background to the right’ are faulty printed on the left page.

**Comment by emmanueltouzery** [comment]
maybe check that my patch does help also in your case?

**Comment by shutterbug79** [comment]
Work like a charm. Thanks

**Comment by AnEnglishmanInNorway** [comment]
@shutterbug79 
Could we close this issue now to keep the list down to issues that are still relevant?

**Comment by AnEnglishmanInNorway** [comment]
Surely this can be closed by now!
