### ISSUE TITLE
Can't convert a CEWE 6.4.7 empty file

### ISSUE THREAD

**Issue by boggiz** [bash0/cewe2pdf#20]
Windows 7 64bits
CEWE 6.4.7
Anaconda Python 3.7.4

Hello,
It's the first time I try this fork of mcf2pdf.
kudos for your work! but I have many errors like these on an empty mcf file:

(base) D:\Cewe2pdf>python cewe2pdf.py "D:\Cewe2pdf\_Albums\Vide.mcf"
parsing page 0  of  28
Could not find ['201.bmp', '201.webp', '201.jpg'] in 
C:\Program Files\UNIVERS Photocite\Logiciel de création CEWE.exe\Resources\photofun\backgrounds, 
C:\Program Files\UNIVERS Photocite\Logiciel de création CEWE.exe\Resources\photofun\backgrounds\einfarbige, 
C:\Program Files\UNIVERS Photocite\Logiciel de création CEWE.exe\Resources\photofun\backgrounds\multicolor, 
C:\Program Files\UNIVERS Photocite\Logiciel de création CEWE.exe\Resources\photofun\backgrounds\spotcolor 
paths error on page 0:
 local variable 'bgpath' referenced before assignment
 (<class 'UnboundLocalError'>, 'cewe2pdf.py', 255)
parsing page 0  of  28
Could not find ['201.bmp', '201.webp', '201.jpg'] in 
C:\Program Files\UNIVERS Photocite\Logiciel de création CEWE.exe\Resources\photofun\backgrounds, 
C:\Program Files\UNIVERS Photocite\Logiciel de création CEWE.exe\Resources\photofun\backgrounds\einfarbige, 
C:\Program Files\UNIVERS Photocite\Logiciel de création CEWE.exe\Resources\photofun\backgrounds\multicolor, 
C:\Program Files\UNIVERS Photocite\Logiciel de création CEWE.exe\Resources\photofun\backgrounds\spotcolor 
paths error on page 1:
 local variable 'bgpath' referenced before assignment
 (<class 'UnboundLocalError'>, 'cewe2pdf.py', 255)
parsing page 2  of  28
Could not find ['201.bmp', '201.webp', '201.jpg'] in 
C:\Program Files\UNIVERS Photocite\Logiciel de création CEWE.exe\Resources\photofun\backgrounds, 
C:\Program Files\UNIVERS Photocite\Logiciel de création CEWE.exe\Resources\photofun\backgrounds\einfarbige, 
C:\Program Files\UNIVERS Photocite\Logiciel de création CEWE.exe\Resources\photofun\backgrounds\multicolor, 
C:\Program Files\UNIVERS Photocite\Logiciel de création CEWE.exe\Resources\photofun\backgrounds\spotcolor 
paths error on page 2:
 local variable 'bgpath' referenced before assignment
 (<class 'UnboundLocalError'>, 'cewe2pdf.py', 255)
parsing page 3  of  28
Could not find ['201.bmp', '201.webp', '201.jpg'] in 
etc ...

Analysing thedirectories shown me that only 201.bmp and 201.webp were present in \einfarbige
I converted 201.bmp to jpeg
So the 3 201.xxx are now in \einfarbige
I start cewe2pdf => KO same errors

I copied the 3 files in all 4 directories
and restart cewe2pdf => KO same errors

Can you tell me what to do ?
Many thank's

**Comment by boggiz** [comment]
I found my error ! 
I left the path to the Cewe program in cewe_folder.txt.
But now I have many errors in fonts. All are replaced by Helvetica !
Why ?

**Comment by chharms** [comment]
You have to place a file "additional_fonts.txt". Contents should be like:
`Bodoni = C:\Program Files\CEWE\RINGFOTO FOTOWELT\Resources\photofun\fonts\Bodoni-Regular.ttf`
(or whatever you use and the path might be).

**Comment by boggiz** [comment]
Thank you for your response. 
All fonts errors are ok now but I have Webp errors.
I read that "conda install libwebp" may correct the problem but no and   "Pip install webp " has many errors. 
Do you know how to do ?

**Comment by BarchSteel** [comment]
@boggiz:
There is a problem with the WEBP support in the Anaconda version of the pillow package.
Try the following: (Type this in your Anaconda prompt)
conda install lxml
conda uninstall reportlab pillow
pip install reportlab pillow

**Comment by AnEnglishmanInNorway** [comment]
@boggiz:
I think we should close this now, since webp support is now included.

**Comment by boggiz** [comment]
Absolutely now that webp is integrated.
Thx
