### ISSUE TITLE
Option to combine pages

### ISSUE THREAD

**Issue by abonne01** [bash0/cewe2pdf#23]
Hello
Thanks for this work. It works fine.
Could you add option to be able to see it more as a book. 
Currently pages are extracted one by one. In my photo books, I usually arrange my picture with the 2 pages, particularly for flat book.
On PDF generated, effect is completely lost.

Thanks a lot.

**Comment by bash0** [comment]
Hello,
currently I'm not continuing the development of the script. If someone wants to take over, this would be great!

**Comment by BarchSteel** [comment]
@abonne01 : try the --keepDoublePages option.

**Comment by abonne01** [comment]
Hi @BarchSteel 

that's excactly that I was looking for..  :) didn't see this option in documentation

Thanks.
