### ISSUE TITLE
UTF-8(?) escaped characters (eg smiley) do not display correctly

### ISSUE THREAD

**Issue by AnEnglishmanInNorway** [bash0/cewe2pdf#45]
Create a text box containing a smiley, as in the attached picture. In the mcf file you will find it represented like this:

> Smiley here: '\ue170'

and it will end up in the pdf looking like this

> Smiley here: ''

even though it appears in the cewe editor as shown in the attached picture. Relevant (maybe) links https://stackoverflow.com/questions/45001829/reportlab-unicode-characters-appear-as-boxes-in-unicode-supported-font
https://www.utf8-chartable.de/unicode-utf8-table.pl?start=57664&utf8=0x
https://docs.python.org/3/howto/unicode.html
https://kaviraj.me/generating-pdf-containing-emoji-python/

![Unicode Annotation 2020-05-04 063231](https://user-images.githubusercontent.com/12747177/80936350-1c422680-8dd1-11ea-820b-d5685cff08bf.jpg)

**Comment by BarchSteel** [comment]
I think that's a bug in CEWE Fotobuch.
Create a new empty fotobook.
Add a text box.
Change Font to Segoe UI Emoji 
Add an Emoji, like 😀 (Unicode Simley 1F600), by Copy&Pase
Save the .mcf file. 
For my CEWE software, the .mcf file does _NOT_ contain the emoji, i.e. the software does not save it.

But cewe2pdf works fine with Simlies:
Use a text editor to add this text box to your .mcf:
```XML
<text applySpotColor="0" areaTextType="content"><![CDATA[<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd"><html><head><meta name="qrichtext" content="1" /><style type="text/css">p, li { white-space: pre-wrap; }</style></head><body style=" font-family:'Segoe UI Emoji'; font-size:12pt; font-weight:400; font-style:normal;">
<table style="-qt-table-type: root; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;"><tr>
<td style="border: none;"><p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">
<span style=" font-size:14pt; color:#000000;">Unicode Simley 1F600</span></p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">
<span style=" font-size:14pt;">here:😀</span></p>
<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; color:#000000;"><br /></p></td></tr></table></body></html>]]><outline width="0"/>
<textFormat Alignment="ALIGNLEFT" IndentMargin="0" VerticalIndentMargin="0" backgroundColor="#00000000" font="Segoe UI Emoji,14,-1,5,50,0,0,0,0,0" foregroundColor="#ff000000" hasOutline="0"/>
</text>
```

Add the following lines to your 'additional_fonts.txt':
```
Segoe UI Emoji = C:\Windows\Fonts\seguiemj.ttf
Segoe UI Emoji,sans-serif = C:\Windows\Fonts\seguiemj.ttf
```

The converted pdf shows the Simely nicely.

The most common pitfall is probably to use a font that does not include the Unicode codepoints for the emoji. Almost all Windows fonts are missing the emoji range.

**Comment by AnEnglishmanInNorway** [comment]
I don't know. I found this issue because I used an emoji in my most recent private album, copying it out of the Windows Character Map application (Segoe MDL2 Assets) and pasting into the text box in Cewe. It shows correctly in the album editor and printed correctly in the paid paper version. 
I've copied that text box into our project unittest_fotobook.mcf (that's where I took the screenshot from in my original issue text) showing that the smiley is correctly displayed by the album editor for our own mcf file. I've now added a few more, also from Segoe UI Emoji. The characters are indeed stored in the mcf file, I've attached a screenshot of the (reformatted) CDATA content in Notepad++ to show them. 

![mcf with emojis Annotation 2020-05-04 185523](https://user-images.githubusercontent.com/12747177/80992808-5562b100-8e3a-11ea-80de-75f6a0c3abda.jpg)

Then, when I break in the debugger just before these text strings are added to Reportlab Paragraph, the last two strings in the debugger look like this:

> "3 more copied in from Windows Character Map, Segoe MDL2 Assets. '\ue170\ue11d\ue137'"
> " '©☹♡'"

Interesting. The MDL2 versions are shown as 2 byte unicodes, while the UI emoji characters actually show as the special characters - both in the debugger and here on the web page!
Also interesting is the fact that the album editor and the official printing process manages to show these special characters correctly despite the fact the mcf file does not seem to say which character set they come from.

Here's how our generated pdf looks for the data above. The copyright symbol works, but not the others.

![our pdf emojis Annotation 2020-05-04 185523](https://user-images.githubusercontent.com/12747177/80992916-893dd680-8e3a-11ea-891e-9cbcce7a5985.jpg)

The fonts registered ok as shown below

> Successfully registered 'Segoe UI Emoji' from 'C:\Windows\Fonts\seguiemj.ttf'
> Successfully registered 'Segoe UI Emoji,sans-serif' from 'C:\Windows\Fonts\seguiemj.ttf'
> Successfully registered 'Segoe MDL2 Assets' from 'C:\Windows\Fonts\segmdl2.ttf'

I'm a bit confused about the font naming. What name should I actually be using in the additionalfonts.txt, and why?

All very mysterious, though not exactly a high priority issue, perhaps!

**Comment by AnEnglishmanInNorway** [comment]
Oh, and there's another issue here, I see, which I guess needs its own issue number ... I have used a frame around the text box, in light blue, as shown in the screenshot from the album editor. We don't show that in the pdf :-(

**Comment by BarchSteel** [comment]
I tried again, now my dm-Foto 7.0.2 does save the text just as-is in the .mcf file. Maybe I made an error the first time.
`` <p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">here:☠☢☹☹☺☺♈♨♥♤</p> ``

Your issue may be related to your version of the software?
What is the languge you have set for your system or keyboard. What does cmd.exe -> chcp   show as codepage?

Your "missing-character-blocks" looks a little like a problem with ANSI encoding in the text file, depending on the locale used to decode it. Can you get to show them using Notepad++->Encodings?

**Comment by AnEnglishmanInNorway** [comment]
I have my system language as English UK, with a Norwegian keyboard. Active
code page 850.
When I copy the two lines of emojis out of the unittest in the album editor
and paste them straight into notepad++ then I see the ones in the second
line (Segoe UI Emoji) but not those from Segoe MDL2 assets. That's
fundamentally the same as what I see here if I paste into this Chrome/gmail
window:

3 more copied in from Windows Character Map, Segoe MDL2 Assets. ''

and 3 from Segoe UI Emoji in larger font '©☹♡'

Let's not use too much time on this for now. At least for me it isn't a
huge deal.

**Comment by BarchSteel** [comment]
Ah, that encoding issue was a false wild-goose chase.

I think I know what's going on after looking at the .mcf file from your repository.
It looks like this:  ```<span style=" font-family:'Arial Rounded MT Bold'; font-size:20pt; color:#000000; background-color:#ffffff;">Smiley here: ''</span>```
That is code-point U+E170 which is in the Private Use Area. (Interestingly, this is encoded as 3 bytes: Encoded as UTF-8 in 3 bytes 0xEE 0x85 0xB0 )
If we stick to the offical current Unicode 13 characters, we could use 😀 U+1F600 "grinning face", or 🙂 U+1F642 "slightly smiling face" instead. But back to the problem:

According to https://www.unicode.org/faq/private_use.html :  "Private-use characters are code points whose interpretation is not specified..."
This means, there is no standard way what to display when such a character should be displayed. 
Again, most Windows fonts don't have a glyph for that code point.
On my Windows 10 I don't have Segoe MDL2 Assets, but I have instead Segoe UI Symbols, which has the smiley U+E170.
All other fonts I tried, including Segore Segoe UI Emoji, and Arial Rounded MT Bold, do not have that character.

Just registering the font with ```Segoe UI Symbols = C:\Windows\Fonts\seguisym.ttf``` and change the font to:
```<span style=" font-family:'Segoe UI Symbols'; font-size:20pt; color:#000000; background-color:#ffffff;">Smiley here: ''</span>``` and it will display correctly!

That brings us back to the CEWE software. Why does it display the Smiley even the a font is selected that does not support that character? I think, they use a heuristic approach and try a few different fonts, or they have a list.

**Comment by AnEnglishmanInNorway** [comment]
You are so right!
All done in the album editor, just set the font for all the symbols to
Segoe UI Symbols and the whole thing looks good, both in the editor:
[image: image.png]
and in the pdf:
[image: image.png]
Nice detective work. I'll check in the modified unittest_fotobook.mcf and
we can close the issue (leaving Cewe's heuristics to them!)
Cheers, Pete
