### ISSUE TITLE
Could we create an installable version of cewe2pdf?

### ISSUE THREAD

**Issue by AnEnglishmanInNorway** [bash0/cewe2pdf#54]
I have shown my PDF photo albums to non-programming friends who then wonder if they could use the same program - so I'm beginning to think a little about how cewe2pdf might be packaged up for use elsewhere. An ex-colleague suggested putting it inside a Docker container, thus making it available on many platforms. I had a first look at Docker technology and have to say it looks neat, providing a full execution environment for the application it contains. Anybody have any experience with or opinions about Docker, in particular used with Python applications? Or any alternative way in which cewe2pdf might be packaged up?

**Comment by BarchSteel** [comment]
I would say that Docker is overkill, or at least one of the least desirable solutions for the end-user.

Instead, just package all the files up into a .exe, and include the python runtime.

There are several options:
see: 
[https://github.com/py2exe/py2exe](https://github.com/py2exe/py2exe)
[https://packaging.python.org/overview/#bringing-your-own-python-executable](https://packaging.python.org/overview/#bringing-your-own-python-executable)
