### ISSUE TITLE
Colored boxes missing

### ISSUE THREAD

**Issue by steff517** [bash0/cewe2pdf#56]
Colored boxes are missing. Example:

**Original**
![image](https://user-images.githubusercontent.com/1554347/101977940-908b5500-3c51-11eb-9013-ea005e28a6cc.png)

**Converted**
![image](https://user-images.githubusercontent.com/1554347/101977879-1bb81b00-3c51-11eb-9d31-d6d8c6813bce.png)

Page source code
`<page rotation="0" type="normalpage" pagenr="48">
  <bundlesize height="2050" width="5400"/>
  <designElementIDs background="159" layout="49904"/>
  <background alignment="1" rotation="0" type="1" templatename="159,normal,"/>
  <background templatename="schema_landscape_059_x-axis, y-axis,normal" layout="1"/>
  <area areaAbilities="114687" left="-30" top="757.8144853875479" height="1322.185514612452" shadowAngle="135" rotation="0" shadowWidthInMM="4" width="1340" areatype="imagearea" shadowDistance="50" shadowEnabled="0" zposition="110" shadowBlurNew="5" alpha="1" shadowIntensity="128">
   <border color="#ffffff" width="20" offset="-10" enabled="1"/>
   <image left="-860" top="0" useABK="0" scale="0.436289" safeContainerLocation="persistent" filename="DSC06639.jpeg">
    <relationships>
     <relationship parent="P:/digicam/2014/08_August/DSC06639.JPG" child="DSC06639.jpeg" nature="RELATIONSHIP_MODIFIED_COPY"/>
    </relationships>
   </image>
  </area>
  <area areaAbilities="114687" left="1310" top="109.0000000000002" height="1831" shadowAngle="135" rotation="0" shadowWidthInMM="4" width="1390" areatype="imagearea" shadowDistance="50" shadowEnabled="0" zposition="111" shadowBlurNew="5" alpha="1" shadowIntensity="128">
   <border color="#ffffff" width="20" offset="-10" enabled="1"/>
   <image left="0" top="-303" useABK="1" scale="0.454843" safeContainerLocation="persistent" filename="DSC06671.jpeg">
    <relationships>
     <relationship parent="P:/digicam/2014/08_August/DSC06671.JPG" child="DSC06671.jpeg" nature="RELATIONSHIP_MODIFIED_COPY"/>
    </relationships>
   </image>
  </area>
  <area areaAbilities="114687" left="-30" top="-30" height="787.8144853875476" shadowAngle="135" rotation="0" shadowWidthInMM="4" width="1340" areatype="imagearea" shadowDistance="50" shadowEnabled="0" zposition="112" shadowBlurNew="5" alpha="1" shadowIntensity="128">
   <border color="#ffffff" width="20" offset="-10" enabled="1"/>
   <image left="0" top="-188" useABK="1" scale="0.410539" safeContainerLocation="persistent" filename="20140823_223614.jpeg">
    <relationships>
     <relationship parent="P:/digicam/2014/08_August/20140823_223614.jpg" child="20140823_223614.jpeg" nature="RELATIONSHIP_MODIFIED_COPY"/>
    </relationships>
   </image>
  </area>
  <area areaAbilities="114687" left="2700" top="-30" height="2110" shadowAngle="135" rotation="0" shadowWidthInMM="4" width="1465" areatype="imagearea" shadowDistance="50" shadowEnabled="0" zposition="113" shadowBlurNew="5" alpha="1" shadowIntensity="128">
   <border color="#ffffff" width="20" offset="-10" enabled="1"/>
   <image left="-91" top="0" useABK="1" scale="0.646446" safeContainerLocation="persistent" filename="20140825_195709.jpeg">
    <relationships>
     <relationship parent="P:/digicam/2014/08_August/20140825_195709.jpg" child="20140825_195709.jpeg" nature="RELATIONSHIP_MODIFIED_COPY"/>
    </relationships>
   </image>
  </area>
  <area areaAbilities="114687" left="4165" top="1064" height="1016" shadowAngle="135" rotation="0" shadowWidthInMM="4" width="1265" areatype="imagearea" shadowDistance="50" shadowEnabled="0" zposition="114" shadowBlurNew="5" alpha="1" shadowIntensity="128">
   <border color="#ffffff" width="20" offset="-10" enabled="1"/>
   <image left="-94" top="-719" useABK="0" scale="0.446338" safeContainerLocation="persistent" filename="1063vc09_1_DSC06694.jpeg">
    <relationships>
     <relationship parent="P:/digicam/2014/08_August/DSC06694.jpg" child="1063vc09_1_DSC06694.jpeg" nature="RELATIONSHIP_MODIFIED_COPY"/>
    </relationships>
   </image>
  </area>
  <area areaAbilities="114687" left="4165" top="-30" height="1094" shadowAngle="135" rotation="0" shadowWidthInMM="4" width="1265" areatype="imagearea" shadowDistance="50" shadowEnabled="0" zposition="115" shadowBlurNew="5" alpha="1" shadowIntensity="128">
   <border color="#ffffff" width="20" offset="-10" enabled="1"/>
   <image left="-44" top="-321" useABK="1" scale="1.13668" safeContainerLocation="persistent" filename="20140827_143739.jpeg">
    <relationships>
     <relationship parent="P:/digicam/2014/08_August/20140827_143739.jpg" child="20140827_143739.jpeg" nature="RELATIONSHIP_MODIFIED_COPY"/>
    </relationships>
   </image>
  </area>
  <area areaAbilities="66303" left="2700" top="1801.517067003792" height="138.4829329962067" shadowAngle="135" rotation="0" shadowWidthInMM="4" width="2878.015836050303" areatype="clipartarea" shadowDistance="50" shadowEnabled="0" zposition="116" shadowBlurNew="5" alpha="0.6" shadowIntensity="128">
   <designElementIDs clipart="63488"/>
   <border color="#000000" width="5" offset="0" enabled="0"/>
   <clipart uniqueName="clipart_rect_cream.svg"/>
  </area>
  <area areaAbilities="66299" left="2699.999999999998" top="1801.517067003792" height="138.4829329962076" shadowAngle="135" rotation="0" shadowWidthInMM="4" width="2650.000000000002" areatype="textarea" shadowDistance="50" shadowEnabled="0" zposition="1000" shadowBlurNew="5" alpha="1" shadowIntensity="128">
   <border color="#000000" width="5" offset="0" enabled="0"/>
   <text isSpineText="0"><![CDATA[<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd"><html><head><meta name="qrichtext" content="1" /><style type="text/css">p, li { white-space: pre-wrap; }</style></head><body style=" font-family:'Function'; font-size:22pt; font-weight:600; font-style:normal;"><table border="0" style="-qt-table-type: root; margin-top:25px; margin-bottom:20px; margin-left:20px; margin-right:20px;"><tr><td style="border: none;"><p align="center" style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" color:#000000;">Mio lässt sich den Urlaub am Bauernhof vom Regenwetter nicht verderben </span></p></td></tr></table></body></html>]]><outline color="#000000" width="1" enabled="0"/>
    <textFormat IndentMargin="20" foregroundColor="4278190080" VerticalIndentMargin="50" font="Function,22,-1,5,75,0,0,0,0,0" backgroundColor="0" Alignment="132"/>
   </text>
  </area>
 </page>`

**Comment by AnEnglishmanInNorway** [comment]
Hi
Just took a very quick look at this. Am I correct in assuming that the
texting here is irrelevant? The "colored box" behind the text is a separate
clipart element, and not the text background, right? So we are probably
chasing an issue with locating and/or displaying an svg file ... <clipart
uniqueName="clipart_rect_cream.svg"/>?
Pete

**Comment by steff517** [comment]
Hi Pete,

that's correct, the background is a separate element behind the text. I removed it in the CEWE Editor and did a diff of the files. This section vanished:

` <area areatype="clipartarea">
            <position height="138.483" left="2700" rotation="0" top="1801.52" width="2878.02" zposition="116"/>
            <designElementIDs clipart="63488"/>
            <decoration alpha="0.59999999999999998"/>
            <clipart designElementId="63488">
                <ClipartConfiguration applySpotColor="0"/>
            </clipart>
        </area>`

Stefan

**Comment by AnEnglishmanInNorway** [comment]
OK. I added a photo, a clipart overlay, and a text describing the situation
to the unittest mcf. And indeed the clipart overlay does not come out in
the pdf, confirming your observation. I'm using version 7.00.04 of the
editor.
I'll push my changes up so we have a checked-in example to work with.
I'm not sure when/if I'll get round to it, if you or anybody else wants to
pick it up.
Good observation, thanks for contributing!
Pete

**Comment by steff517** [comment]
I found out that the clipartID 63488 is not listed in cliparts_default.xml probably because this box is not an image but just a color. 
I see this error in the log: Problem getting file name for clipart ID: 63488
Here's the piece of code which exits after the error. 

`if (not fileName):
        print("Problem getting file name for clipart ID:", clipartID)
        return`

**Comment by AnEnglishmanInNorway** [comment]
Just ran the unittest I had modified in a debugger and realized that I had been fooled by a special version of cewe2pdf.ini in the tests folder (and had failed to notice an error message about the missing clipart id which you just saw). So I replaced the special version of with the normal cewe2pdf.ini from the main directory and bingo, there was my clipart triangle, clipart id 121605 (though it was not semi transparent, which I guess is really a different issue).
I had a look in my installed C:\Program Files\...\Resources\photofun\decorations\cliparts_default.xml and didn't find your clipart id 63488 there. How did you actually insert your box as "just a color" using the editor?

**Comment by steff517** [comment]
Unfortunately this photobook is 5 years old, so I can't really tell anymore what I inserted...

**Comment by AnEnglishmanInNorway** [comment]
I just found that too. I tried downloading all the colours using the UI that you show, but still there was no colour id 63488 in the xml. It does seem unlikely that they have dropped a colour from an old version, but it certainly looks a bit that way. Have you tried replacing your box with a new one using one of today's colours? I can choose colours from the UI you show and they display OK, excepting the transparency issue.  We're definitely missing handling for the alpha value but I'm afraid my knowledge of image processing is too weak to fix that quickly. I can maybe see that we need to do something near the convertToPngInBuffer call in the code, but at that point I get unstuck. Perhaps somebody else listening knows more about this?

**Comment by AnEnglishmanInNorway** [comment]
Alternatively, if you have a **lot** of boxes with id 63488, you could edit your cliparts_default.xml file. I did that, making a copy of the entry for 63504 (rect_lightyellow.svg) and changing it to have the id 63488. Then I edited my test mcf file to reference 63488 rather than 63504, and - not surprisingly - I got my light yellow rectangles. Still not transparent, though :-(

**Comment by AnEnglishmanInNorway** [comment]
One final remark before I really do have to go. After some googling I think the clue with transparency is going to be adding a line in convertToPngInBuffer to use the putalpha method just before we save scaledImage, something like:
` scaledImage.putalpha(alpha)`
We can pick the alpha attribute out of the decoration tag, turn it into a value between 0 and 255, and pass it in to this call. 
I tested it with a hard coded value of 128, which gave me about 50% transparency on all my cliparts. 
However, this is unfortunately not the full solution, because if the clip is not a rectangle then it gets "filled out" to a rectangle with black, as you can see in the picture. I think this means we have to make a mask image to use instead of a simple value, but now I'm unstuck again.
![Screenshot 2020-12-14 104521](https://user-images.githubusercontent.com/12747177/102066022-96bc3580-3df9-11eb-9591-2a24717c8275.jpg)

**Comment by steff517** [comment]
I did some more testing and create a new photobook inserting only this clipart:
![image](https://user-images.githubusercontent.com/1554347/102055198-c57edf80-3dea-11eb-86e0-c75c8278b257.png)

In the source it turns out as 63488 again. 
[test.zip](https://github.com/bash0/cewe2pdf/files/5688236/test.zip)

**Comment by steff517** [comment]
I searched my PC for the number and found this:
[63488.zip](https://github.com/bash0/cewe2pdf/files/5688292/63488.zip)
Bingo. 
Located in C:\ProgramData\hps\6822\addons

**Comment by AnEnglishmanInNorway** [comment]
Nice detective work. Looks like that's the location for all sorts of downloaded content. A similar problem with downloaded backgrounds was dealt with it by adding the _extraBackgroundFolders_ section to the cewe2pdf.ini file. Perhaps the solution to locating these downloaded cliparts would be to add a similar section, say _extraClipArtFolders_, and extend the clip art folder processing in a similar way so that cewe2pdf can find the extra files. That would be preferable to taking the contents of the downloaded data and somehow manually merging it into the main stuff (not least because any change we might make locally to Cewe installed files - as I hinted at above - would most likely be lost on a version upgrade)
I suppose, if we can understand how Cewe think around download locations, that it might be possible to generalise out from _extraSomethingFolders_ to just _extraFolders_, so we didn't have to specify all the various extra folders individually.

**Comment by steff517** [comment]
I found this file:
`C:\ProgramData\hps\6822\filehash.txt`
It seems to list all CEWE ressources. Do you have that, too? This would be quite handy. It might even be independant from the install location of CEWE.

**Comment by AnEnglishmanInNorway** [comment]
Yes - and no.
I have found filehash.txt, but in my case all the cewe stuff comes under
  C:\ProgramData\hps\5026
I wonder how they choose the magic number.
The same number appears as part of the filename for 6 files in the
installation directory, which of course is named for the local company
which is selling the service using cewe, in my case:
  C:\Program Files\Elkjop fotoservice_6.3\elkjop fotoservice\Resources
The files in question being
  deliverytimes-5026-2.3.xml
  orderingdetails-5026-2.3.xml
  prices-5026-2.3.xml
  products-5026-2.3.xml
  resources-5026-2.3.xml
  terms-5026-2.3.xml
Perhaps it's a franchise number, since things like delivery times and
prices would probably vary per franchise. If that was the case, then we
might be able to find the names of all the things we need based on one
entry in the cewe2pdf.ini file, namely this magic number!
Pete

**Comment by steff517** [comment]
It looks like so! 
![image](https://user-images.githubusercontent.com/1554347/102105956-4b714980-3e30-11eb-944a-e1c1c3208b0c.png)

**Comment by steff517** [comment]
I see it in the path. You service also has the keyaccount ID in the website source.

**Comment by AnEnglishmanInNorway** [comment]
Mmm. I had two versions of the CEWE software installed at one time. I see now that there are two directories under hps, the 5026 one I have talked about above, and one for 28611, which matches the key account id you can see in the source at www.cewe.no. And under each of those there are directories which match the program version numbers used from that supplier. So they can add (and/or replace?) stuff by supplier and by version. You've got to admire the work they must be putting in to maintaining a customisable program across so many countries and companies. Now all we have to do is work out if there is a good way of making use of this discovery!

**Comment by steff517** [comment]
My suggestion:
To fix this issue: Configure and/or build the path to keyaccount.xml and read the ID to figure out the folders with missing SVGs.
Premium solution: Setup-Script to scan program-files folder and configure path automatically.

**Comment by AnEnglishmanInNorway** [comment]
Do you want to do it? I'm a bit pushed to invest much time in programming right now. 
We should perhaps coordinate the lookup of svgs with a lookup of backgrounds, which are currently more explicitly configured with the _extraBackgroundFolders_ list in the ini file. Alternatively, I guess, we could just do a keyword substitution on the strings in the _extraBackgroundFolders_ list, eg 
`C:/ProgramData/hps/5026/addons/447/backgrounds/v1/backgrounds`
might become 
`%PROGRAMDATA%/hps/%KEYACCOUNT%/addons/447/backgrounds/v1/backgrounds`
with substitutions from the environment and from our own set of keywords.

**Comment by steff517** [comment]
Unfortunately I can't really code python. It'd help to add the alpha support, if that's a quick fix. 
I can solve everything with a workaround myself.

**Comment by AnEnglishmanInNorway** [comment]
OK. I'll see what I can do for the alpha factor to begin with. What I am concerned about is that it might change the existing behaviour for non rectangular clips. If it does, then we really need to find a better solution. If it doesn't then it will at least fix your problem with the rectangular clips. No promise on delivery time...

**Comment by AnEnglishmanInNorway** [comment]
First try here https://github.com/bash0/cewe2pdf/pull/57

**Comment by steff517** [comment]
Great, I can confirm that the creme-colored box behind the text is rendered correctly now.
The black boarders are not solved.
