### ISSUE TITLE
I got the background attribute in uppercase

### ISSUE THREAD

**Issue by emmanueltouzery** [bash0/cewe2pdf#6]
in my MCF file (version 4008007), the background attribute is uppercase, like so:

```
<designElementIDs BACKGROUND="201" LAYOUT="33873"/>
```

But cewe2pdf is searching for lowercase 'background' and so not finding the attribute. I replaced the lowercase get() by the uppercase and it works great. I don't know python very well and didn't find a nice way to check both attributes though. I would make the code a little uglier by checking both. Maybe you know a nicer way?

**Comment by AnEnglishmanInNorway** [comment]
@emmanueltouzery
I think we should close this now! Just tried on today's version, manually replacing background="201" with BACKGROUND="201" in the unittest fotobook, and temporarily changing the colour of the 201.jpg file to be sure that it was being found. Everything is ok now.

**Comment by emmanueltouzery** [comment]
ok, let's close then
