### ISSUE TITLE
Should we provide a GUI in front of cewe2pdf?

### ISSUE THREAD

**Issue by AnEnglishmanInNorway** [bash0/cewe2pdf#75]
Suppose you have followed the instructions and created an "installation" structure which can be taken to another machine. And that the user of the other machine is not a programmer who is familiar with executing programs from the command line. Would it be a good idea to create a very simple (separate) graphical frontend? A minimal solution could simply allow the user to browse to and select an .mcf file, and then press a button to process the file (as a background call to the command line _cewe2pdf.exe_), perhaps with an option to specify a final location for the pdf.
If we think a GUI is a good idea, which Python UI package would be sensible? My first search hit _PySimpleGui_ but there are clearly many alternatives, https://wiki.python.org/moin/GuiProgramming 
Anybody have an opinion?

**Comment by bash0** [comment]
If it must have a GUI, it has to be something that goes without installation of additional packages, and run on all major platforms. Otherwise it makes things more complicated instead of simpler.

**Comment by AnEnglishmanInNorway** [comment]
I agree. My thought was to have a separate GUI which would call the underlying _cewe2pdf.exe_ to do the job. My programming in Python is limited to this project, but you can do this in other languages/environments so I figured there must be a way to do it in a system independent way in Python as well. The discussion linked below seems to suggest that _subprocess.run_ might be the way to go. But of course I'm open to other ideas!
https://stackoverflow.com/questions/89228/how-to-execute-a-program-or-call-a-system-command-from-python

**Comment by bash0** [comment]
No, opening a new process with subprocess is not necessary here. One can use a normal function call. On the GUI list you linked, only TkInter seems to be in the standard library. So that would be the option of choice.

**Comment by AnEnglishmanInNorway** [comment]
It's not really a question of necessity, more of a way of achieving a good separation. 
The advantage of using a separate _cewe2pdfui_ process is that the complexity of the UI is kept completely separate from _cewe2pdf_ itself. The one application can be developed entirely separately from the other, leaving the only interface between them as command line arguments. _cewe2pdf_ remains exactly as it is, unaffected by the presence of a GUI, which (I think) is what is worrying you. In fact, it would be quite possible to create the UI program in a different project, though I would vote against that so that it would be easy to package the command line program and the UI program in the same installation package. (On Windows the distribution structure created by pyinstaller, as described by @BarchSteel, was easy to wrap into a "click and install" setup program using InnoSetup) 
Also, my gut feeling is that a simpler UI builder than the full power TkInter would be more than enough and choosing to use that in a separate UI process would also avoid your concern about non standard extra packages in the main program.

**Comment by BarchSteel** [comment]
I never did any Pyhton GUI programming, but I would go for the "industry standard" and use what everybody uses: 
First choice: Python bindings for QT
Second choice: Python bindings for GTK
Reasons: Like I said, I think these are the most common. Lot's of tutorials, help, etc.. Strong support. Many big projects use these. Of course I'm aware of the downsides of complexity and file size.

**Comment by AnEnglishmanInNorway** [comment]
A long long time ago Apollo Computers had their own version of Unix, called Aegis, which had some really nice features. But they were bought up by HP in 1989 and as a result moved to a more standardised Unix, under the slogan "`Standard is better than better`". I've always liked that slogan - in the long run you have to be really good and really powerful to ignore standards. So yes, industry standard is the way to go. I see two candidates, PyQT5 and Pyside. I don't think it's a big deal, given the simplicity, but given Qt's endorsement of Pyside6 (https://doc.qt.io/qtforpython/) my inclination is to go for that.

**Comment by AnEnglishmanInNorway** [comment]
Not much enthusiasm for this idea in the group, but before I close the issue I'll record that I have used PySimpleGui to create my own seriously minimal gui, with plenty of restrictions in how it is used. It simply allows the non-programmer user to browse for an mcf file and then executes cewe2pdf.exe on that file, presenting the output in a window. 

Make an executable cewe2pdfgui.exe with "pyinstaller --onefile cewe2pdfgui.py". Put it together with the mcf file, along with the cewe2pdf.exe you have made similarly and the configuration files {cewe2pdf.ini, additional_fonts.txt, loggerconfig.yaml}
Running cewe2pdfgui.exe is really just like running cewe2pdf.exe in a cmd window, but it feels a bit more "Windows-like" by allowing a non-programmer to browse for the mcf file and process it!

'
    import os.path as path
    import PySimpleGUI as sg
    import subprocess as sub
    import sys

    sg.theme("DarkTeal2")
    layout = [[sg.Text("Choose album file: "), 
               sg.Input(size=75, expand_x=True), 
               sg.FileBrowse(file_types=(("Cewe album files", "*.mcf"),), key="-IN-"), 
               sg.Push(),
               sg.Button("Submit")],
              [sg.Output(size=(120, 8), expand_y=True, expand_x=True, key = '_output_')],
             ]
    window = sg.Window('Cewe MCF to PDF converter', layout, size=(850,400), resizable=True)
    
    while True:
        event, values = window.read()
        if event == sg.WIN_CLOSED or event=="Exit":
            break
        elif event == "Submit":
            # clear output so that the content applies only to the latest submit
            window.FindElement('_output_').Update('')
        
            # for now assume that the program and config files are with the album
            mcffile = values["-IN-"]
            dirname = path.dirname(mcffile)
            mcfname = path.basename(mcffile)
            command = f'cd /d {dirname} && .\\cewe2pdf.exe ' + mcfname
            print(f'executing command: {command}')
        
            with sub.Popen(command, shell=True, stdout=sub.PIPE, stderr=sub.STDOUT, text=True) as proc:
                # line by line output from popen is discussed extensively on the net, with no "perfect"
                # solution. https://stackoverflow.com/questions/2804543/read-subprocess-stdout-line-by-line
                # seems the neatest. It works with Output, but not with Multiline, but I don't know why. At
                # least that seems to confirm that the logger output from cewe2pdf is not buffered.
                while True:
                    line = proc.stdout.readline()
                    if not line:
                        break               
                    sys.stdout.write(line) # prints without new line, unlike print(line) 
    window.Close
'
