### ISSUE TITLE
Separate debug messages from errors

### ISSUE THREAD

**Issue by cweiske** [bash0/cewe2pdf#82]
The cewe2pdf output is very confusing. Errors, warnings and debug messages are all get printed to stdout, which makes it hard to spot the actual errors.

It would be nice if cewe2pdf would:

- send errors to stderr instead of stdout
- always show rendering progress ("parsing page 23 of 42") unless `--quiet` is given
- provide a `--verbose` flag to show messages that are only relevant for developers (e.g. which clipart is used)

cewe2pdf should also show the total number of errors/warnings at the end.

**Comment by AnEnglishmanInNorway** [comment]
I have used various kinds of "loggers" to solve the problem of separating various levels of message (typically _debug_, _info_, _warning_, _error_ or similar) and various groupings of messages (e.g. from various modules or logical sections, in our case perhaps "general", "font handling", "clipart handling", etc though that might be overkill). 
The Apache log4j system set a standard, and the log4net variant was used with success where I worked. 
A quick search revealed that Python actually has its own similar logging system which seems well regarded.
https://opensource.com/article/17/9/python-logging
https://realpython.com/python-logging/
https://www.toptal.com/python/in-depth-python-logging
If we are going to tidy up the output I wonder if it would be worth switching away from print statements to Python logging? Then we could filter the output level appropriately?

**Comment by cweiske** [comment]
Yes. We should ditch print and use the logging module.

**Comment by AnEnglishmanInNorway** [comment]
Any preferences or ideas from previous experience with loggers?  I thought the Python YAML logging configuration looked OK. I tried something like the example below in our code to classify the level and subject of log messages. 
```
def configureLogging():
    import logging
    import logging.config
    import yaml
    with open('loggerconfig.yaml', 'r') as f:
        config = yaml.safe_load(f.read())
        logging.config.dictConfig(config)
```
```
    # initially set up various topic loggers...
    configureLogging()
    mainlogger = logging.getLogger(__name__ + ".main")
    fontlogger = logging.getLogger(__name__ + ".fonts")
```
Then the font registration could be logged as below. The main logger entries say that registration is being done, and would normally always be shown. The font logger entries are only interesting if you are working on a font issue.
```
    # Add additional fonts. We need to loop over the keys, not the list iterator, so we can delete keys from the list in the loop
    mainlogger.info("Starting registration of %s additional fonts" % len(additional_fonts))
    for curFontName in list(additional_fonts):
        try:
            pdfmetrics.registerFont(TTFont(curFontName, additional_fonts[curFontName]))
            fontlogger.info("Successfully registered '%s' from '%s'" % (curFontName, additional_fonts[curFontName]))
        except:# noqa: E722
            fontlogger.error("Failed to register font '%s' (from %s)" % (curFontName, additional_fonts[curFontName]))
            del additional_fonts[curFontName]    # remove this item from the font list, so it won't be used later and cause problems.
    mainlogger.info("Ended additional font registration")
```
The logger configuration would then be in the local file loggerconfig.yaml, which might look like this (unashamedly copied and bastardised from https://realpython.com/python-logging/#basic-configurations with a little help from https://fangpenlin.com/posts/2012/08/26/good-logging-practice-in-python/): 
```
version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  cewe2pdf.main:
    level: INFO
    handlers: [console]
    propagate: no
  cewe2pdf.fonts:
    level: WARNING
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console]
```
With that configuration (and no font errors!) the output for font registration in a normal run was just
```
2021-07-25 22:29:06,831 - cewe2pdf.main - INFO - Starting registration of '378' additional fonts
2021-07-25 22:29:27,020 - cewe2pdf.main - INFO - Ended additional font registration
```
Actually I think the timestamps are a bit overdone in our case, so we could take them off.

**Comment by cweiske** [comment]
I think this is overkill. We don't need  special font loggers or so.

Simply use logging.debug/.info/.warning/.error and control the display with some command line flags.

**Comment by AnEnglishmanInNorway** [comment]
I disagree. When a programmer is working on a particular area of the code the debug diagnostics for some completely separate logic are just as much an irritation as they are in normal program use - the original issue. For instance, debug logging for graphics will usually be irrelevant if the area of interest is text processing.

I don't see the problem with multiple logger names / instances. In general programs are split into logical sections/modules/whatever, surely it is not strange to want to split the associated logging? I'll agree we could have done more here (an almost inevitable effect in a program that grows gradually) but somebody has felt the need to separate the logic of clpfile.py and passepartout.py.

How about a compromise starting with three logger names:

- **cewe2pdf** - the root logger, the default for anything not obviously belonging to the following two logs
- **cewe2pdf.text** - logging of handling of texts, including fonts if you insist, though personally I'd would prefer to be able to turn off 400 lines of font startup tracing if I was looking for a text layout problem
- **cewe2pdf.graphics** - logging of handling of the actual photos, cliparts, masks, etc
though perhaps somebody else may want to comment here?

**Comment by AnEnglishmanInNorway** [comment]
I think/hope we could close this now?

**Comment by AnEnglishmanInNorway** [comment]
With no feedback on this, or on my implementation, I'm going to close it.

**Comment by cweiske** [comment]
Thanks for your work. I'll look into it when I have the next PDF to produce :)
