### ISSUE TITLE
Color replacement in path clipart without color

### ISSUE THREAD

**Issue by cweiske** [bash0/cewe2pdf#85]
The cewe software allows to replace colors in cliparts, at least with version 7.1.2.

The XML looks so:
```
            <clipart designElementId="125765">
                <ClipartConfiguration applySpotColor="0">
                    <colors>
                        <color source="#78ba97" target="#1b7dd4"/>
                        <color source="#845f5d" target="#845f5d"/>
                        <color source="#f06d63" target="#55007f"/>
                        <color source="#f9f8ef" target="#f9f8ef"/>
                    </colors>
                </ClipartConfiguration>
            </clipart>
```

This is currently not supported.

**Comment by AnEnglishmanInNorway** [comment]
I thought this had been addressed in https://github.com/bash0/cewe2pdf/issues/63. You might want to look at that to see if it missed something.

**Comment by cweiske** [comment]
Ah. Clipart `298101` is a single path without any color information. Color replacements don't work there :)

**Comment by AnEnglishmanInNorway** [comment]
Thought I'd have a look at this but I don't seem to have clipart 298101. Is it a downloaded clip? @cweiske maybe you could give me an idea of which one it is? Or even let me have the definition?

**Comment by cweiske** [comment]
I think this is the one that I manually modified by adding the style attribute:
![298101-white](https://github.com/bash0/cewe2pdf/assets/59036/b9b734b8-a563-41e3-92a4-4620b9afc469)

I don't have another one.
